---

- name: Ensure availability of dbus on Debian
  apt: pkg=dbus state=present
  when: ansible_os_family == 'Debian'

- name: Hostname | Update the hostname (pt. 1) - hostname cmd
  hostname:
    name: "{{inventory_hostname_short}}"

- name: Hostname | Update the hostname (pt. 2) - (/etc/hostname)
  copy:
    content: "{{inventory_hostname_short}}{{'\n'}}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644

- name: Hostname | Update the IPv4 hostname (pt. 3) - (/etc/hosts)
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1"
    line: "127.0.0.1{{'\t'}}{{inventory_hostname}}{% if inventory_hostname != inventory_hostname_short %}{{'\t'}}{{inventory_hostname_short}}{% endif %}{{'\t'}}localhost"
    state: present

- name: Hostname | Update the IPv6 hostname (pt. 3) - (/etc/hosts)
  lineinfile:
    dest: /etc/hosts
    regexp: "^::1"
    line: "::1{{'\t\t'}}{{inventory_hostname}}{% if inventory_hostname != inventory_hostname_short %}{{'\t'}}{{inventory_hostname_short}}{% endif %}{{'\t'}}localhost ip6-localhost ip6-loopback"
    state: present
