---

##########################################################################
# Configuration options for the Plone Ansible Playbook
# All these are discussed in the documentation.
#
# Unless you have forked your playbook, you should probably not customize
# this file, as changes will be overwritten by pulls.
#
# Instead, create and edit local-configure.yml
##########################################################################


#######################################
# System options

admin_email:

motd: |
    This server is configured via Ansible.
    Do not change configuration settings directly.

auto_upgrades: yes

additional_packages: []


#######################################
# Plone options

plone_major_version: 4.3

plone_version: 4.3.6

plone_python_version: 2.7

plone_target_path: /usr/local/plone-{{ plone_major_version }}

plone_var_path: /var/local/plone-{{ plone_major_version }}

plone_backup_path:

plone_instance_name: zeoserver

plone_buildout_git_repo: no

plone_buildout_git_version: master

plone_initial_password:

plone_client_count: 2

plone_zodb_cache_size: 30000

plone_zserver_threads: 1

plone_client_max_memory: 0

# plone_additional_eggs:
#     - Products.PloneFormGen

# plone_additional_versions:
#      - "Products.PloneFormGen = 1.7.16"
#      - "Products.PythonField = 1.1.3"
#      - "Products.TALESField = 1.1.3"

plone_zeo_port: 8100

plone_client_base_port: 8081

plone_environment_vars:
  - "PYTHON_EGG_CACHE {{ plone_var_path }}/.python-eggs"

plone_autorun_buildout: yes

plone_buildout_cache_url: http://dist.plone.org/release/{{ plone_version }}/buildout-cache.tar.bz2

plone_buildout_cache_file:


#######################################
# Cron jobs

plone_pack_at:
  minute: 30
  hour: 1
  weekday: 7

plone_keep_days: 3

plone_backup_at:
  minute: 30
  hour: 2
  weekday: "*"

plone_keep_backups: 3

plone_keep_blob_days: 21


#######################################
# Load-balancer options

install_loadbalancer: yes

loadbalancer_port: 8080

loadbalancer_monitor_port: 1080


#######################################
# Caching proxy options

install_proxycache: yes

proxycache_port: 6081

proxycache_method: malloc

proxycache_size: 256m


#######################################
# Web-server options

install_webserver: yes

webserver_virtualhosts:
  - hostname: "{{ inventory_hostname }}"
    aliases:
      - default
    zodb_path: /Plone


#######################################
# Mail-server options

install_mailserver: yes

mailserver_relayhost:

mailserver_relayport:

mailserver_relayuser:

mailserver_relaypassword:


#######################################
# Monitoring options

install_muninnode: yes

munin_node_port: 4949

muninnode_query_ips: []

install_logwatch: yes

install_fail2ban: yes


#########################
# Supervisor options

supervisor_config_dir: "/etc/supervisor/conf.d/"
redirect_stderr: "false"
autorestart: "unexpected"
startsecs: 1
stopwaitsecs: 10
autostart: "true"
task_env_vars: {}
